from billiard import process

W_NO_EXECV: str

class BaseContext:
    def freeze_support(self) -> None: ...
    def allow_connection_pickling(self) -> None: ...

class Process(process.BaseProcess): ...
class DefaultContext(BaseContext): ...
class ForkProcess(process.BaseProcess): ...
class SpawnProcess(process.BaseProcess): ...
class ForkServerProcess(process.BaseProcess): ...

class ForkContext(BaseContext):
    Process = ForkProcess

class SpawnContext(BaseContext):
    Process = SpawnProcess

class ForkServerContext(BaseContext):
    Process = ForkServerProcess
