from billiard.process import BaseProcess

__all__ = ["Popen"]

class Popen:
    method: str
    returncode: int | None
    pid: int
    sentinel: int | None

    def __init__(self, process_obj: BaseProcess) -> None: ...
    def duplicate_for_child(self, fd: int) -> int: ...
    def poll(self, flag: int = ...) -> int | None: ...
    def wait(self, timeout: float | None = ...) -> int | None: ...
    def terminate(self) -> None: ...
    def close(self) -> None: ...
