from _typeshed import Incomplete

__all__ = ['BaseProcess', 'Process']

class BaseProcess:
    def __init__(self, group: Incomplete | None = None, target: Incomplete | None = None, name: Incomplete | None = None, daemon: Incomplete | None = None) -> None: ...
    def run(self) -> None: ...
    def start(self) -> None: ...
    def close(self) -> None: ...
    def terminate(self) -> None: ...
    def terminate_controlled(self) -> None: ...
    def join(self, timeout: Incomplete | None = None) -> None: ...

class AuthenticationString(bytes): ...

class _MainProcess(BaseProcess):
    def __init__(self) -> None: ...
Process = BaseProcess
