from kombu.asynchronous.hub import Hub

def callback_for(h: Hub, fd: int, flag: int) -> str: ...
def repr_flag(flag: int) -> str: ...
def repr_active(h: Hub) -> str: ...
def repr_events(h: Hub, events: list[tuple[int, int]]) -> str: ...
