from collections.abc import Callable, Generator
from typing import Any

from kombu.asynchronous.timer import Timer

__all__ = ("Hub", "get_event_loop", "set_event_loop")

class Hub:
    timer: Timer
    readers: dict[int, Callable[..., Any]]
    writers: dict[int, Callable[..., Any]]
    on_tick: list[Callable[..., Any]]
    on_close: list[Callable[..., Any]] | None

    def __init__(self, timer: Timer | None = ...) -> None: ...
    def __enter__(self) -> Hub: ...
    def __exit__(self, *exc_info: Any) -> None: ...
    def add(
        self,
        fd: int | Any,
        callback: Callable[..., Any],
        flags: int,
        args: tuple[Any, ...] = ...,
        consolidate: bool = ...,
    ) -> None: ...
    def add_reader(
        self, fd: int | Any, callback: Callable[..., Any], *args: Any
    ) -> None: ...
    def add_writer(
        self, fd: int | Any, callback: Callable[..., Any], *args: Any
    ) -> None: ...
    def remove(self, fd: int | Any) -> None: ...
    def remove_reader(self, fd: int | Any) -> None: ...
    def remove_writer(self, fd: int | Any) -> None: ...
    def run_forever(self) -> None: ...
    def run_once(self, timeout: float | None = ...) -> None: ...
    def call_soon(self, callback: Callable[..., Any], *args: Any) -> Any: ...
    def call_later(
        self, delay: float, callback: Callable[..., Any], *args: Any
    ) -> Any: ...
    def call_at(
        self, when: float, callback: Callable[..., Any], *args: Any
    ) -> Any: ...
    def call_repeatedly(
        self, interval: float, callback: Callable[..., Any], *args: Any
    ) -> Any: ...
    def close(self) -> None: ...
    def stop(self) -> None: ...
    def fire_timers(self, min_delay: float = ..., max_delay: float = ...) -> float: ...
    def create_loop(self) -> Generator[None, None, None]: ...

def get_event_loop() -> Hub | None: ...
def set_event_loop(loop: Hub | None) -> Hub | None: ...
