from collections.abc import Callable
from typing import Any

__all__ = ("DummyLock", "LaxBoundedSemaphore")

class DummyLock:
    def __enter__(self) -> DummyLock: ...
    def __exit__(self, *exc_info: Any) -> None: ...
    def acquire(self) -> bool: ...
    def release(self) -> None: ...

class LaxBoundedSemaphore:
    initial_value: int
    value: int

    def __init__(self, value: int) -> None: ...
    def acquire(
        self, callback: Callable[..., Any], *partial_args: Any, **partial_kwargs: Any
    ) -> bool: ...
    def release(self) -> None: ...
    def grow(self, n: int = ...) -> None: ...
    def shrink(self, n: int = ...) -> None: ...
    def clear(self) -> None: ...
