#!/bin/bash

set -ex

# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check .
    ./.venv/bin/isort --check-only
else
    ./.venv/bin/black .
    ./.venv/bin/isort .
fi

./node_modules/.bin/pyright typings tests

# type check code
./.venv/bin/mypy tests

# lint
./.venv/bin/flake8 tests

