#!/bin/bash

set -ex

# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check .
    ./.venv/bin/ruff .
else
    ./.venv/bin/black .
    ./.venv/bin/ruff . --fix
fi

./node_modules/.bin/pyright typings tests

# type check code
./.venv/bin/mypy tests
