#!/bin/bash

set -ex

# format code
if [[ $CI ]]; then
    ./.venv/bin/ruff format --check .
    ./.venv/bin/ruff check .
else
    ./.venv/bin/ruff format .
    ./.venv/bin/ruff check . --fix
fi

./.venv/bin/basedpyright typings tests

# type check code
./.venv/bin/mypy tests
