from typing import Any, TypeVar

from kombu.connection import Connection
from kombu.transport.base import StdChannel

__all__ = ("Object", "MaybeChannelBound")

_MaybeChannelBoundT = TypeVar("_MaybeChannelBoundT", bound="MaybeChannelBound")

class Object:
    attrs: tuple[tuple[str, Any], ...]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __copy__(self) -> Object: ...
    def as_dict(self, recurse: bool = ...) -> dict[str, Any]: ...

class MaybeChannelBound(Object):
    @property
    def can_cache_declaration(self) -> bool: ...
    def __call__(
        self: _MaybeChannelBoundT, channel: StdChannel | Connection
    ) -> _MaybeChannelBoundT: ...
    def bind(
        self: _MaybeChannelBoundT, channel: StdChannel | Connection
    ) -> _MaybeChannelBoundT: ...
    def maybe_bind(
        self: _MaybeChannelBoundT, channel: StdChannel | Connection
    ) -> _MaybeChannelBoundT: ...
    def revive(self, channel: StdChannel) -> None: ...
    def when_bound(self) -> None: ...
    @property
    def channel(self) -> StdChannel: ...
    @property
    def is_bound(self) -> bool: ...
