from typing import Any

from kombu.entity import Exchange, Queue
from kombu.messaging import Consumer as _Consumer
from kombu.messaging import Producer

__all__ = ("Publisher", "Consumer")

class Publisher(Producer): ...

class Consumer(_Consumer): ...

class ConsumerSet:
    def __init__(self, connection: Any, *args: Any, **kwargs: Any) -> None: ...
    def add_consumer(self, consumer: _Consumer) -> None: ...
    def iterconsume(self, limit: int | None = ..., no_ack: bool = ...) -> Any: ...
    def discard_all(self) -> int: ...
    def close(self) -> None: ...

def entry_to_queue(queue: str, **options: Any) -> Queue: ...
