from logging import Handler, Logger
from typing import Any

__all__ = ("LogMixin", "LOG_LEVELS", "get_loglevel", "setup_logging")

LOG_LEVELS: dict[str, int]

class Log:
    logger: Logger
    _logger: Logger | None

    def __init__(self, name: str | None = ..., logger: Logger | None = ...) -> None: ...
    def debug(self, *args: Any, **kwargs: Any) -> None: ...
    def info(self, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, *args: Any, **kwargs: Any) -> None: ...
    def error(self, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, *args: Any, **kwargs: Any) -> None: ...

class LogMixin:
    @property
    def logger(self) -> Logger: ...

def get_loglevel(level: str | int) -> int: ...
def setup_logging(
    loglevel: int | str | None = ..., logfile: str | None = ...
) -> None: ...
def get_logger(logger: str | Logger) -> Logger: ...
