from collections.abc import Callable
from typing import Any

class MatcherNotInstalled(Exception): ...

class MatcherRegistry:
    def __init__(self) -> None: ...
    def register(self, name: str, matcher: Callable[..., bool]) -> None: ...
    def unregister(self, name: str) -> None: ...
    def match(
        self,
        data: bytes,
        pattern: bytes,
        matcher: str | None = ...,
        matcher_kwargs: dict[str, str] | None = ...,
    ) -> bool: ...

def match(
    data: bytes,
    pattern: bytes,
    matcher: str | None = ...,
    matcher_kwargs: dict[str, str] | None = ...,
) -> bool: ...
def register(name: str, matcher: Callable[..., bool]) -> None: ...
def unregister(name: str) -> None: ...
def register_glob() -> None: ...
def register_pcre() -> None: ...
