from celery.concurrency.asynpool import AsynPool
from celery.concurrency.base import BasePool

__all__ = ["TaskPool"]

class TaskPool(BasePool):
    Pool = AsynPool
    uses_semaphore: bool
    def on_start(self) -> None: ...
    def restart(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_terminate(self) -> None: ...
    def on_close(self) -> None: ...
