class AMQPError(Exception): ...
class ConnectionError(AMQPError): ...
class ChannelError(AMQPError): ...
class RecoverableChannelError(ChannelError): ...
class IrrecoverableChannelError(ChannelError): ...
class RecoverableConnectionError(ConnectionError): ...
class IrrecoverableConnectionError(ConnectionError): ...
class ResourceError(RecoverableConnectionError): ...
